# Generated by Django 4.1.6 on 2023-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator1', models.CharField(max_length=50)),
                ('operand', models.CharField(max_length=50)),
                ('operator2', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
