# Generated by Django 4.1.6 on 2023-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_mc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mc',
            new_name='Memory',
        ),
    ]
