# Generated by Django 4.1.6 on 2023-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_rename_mc_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='operand1',
        ),
        migrations.RemoveField(
            model_name='history',
            name='operand2',
        ),
        migrations.RemoveField(
            model_name='history',
            name='operator',
        ),
        migrations.AddField(
            model_name='history',
            name='operation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
